### PR TITLE
Set the "mod_sftp.file-status" note in more cases when the OPEN reque…

### PR DESCRIPTION
**Pull request by Castaglia**
…st is

rejected/failed for any reason.  Addresses Issue #430 .

### CODE REVIEW

**Comment by tspicer** [comment]
here are some log snapshots
https://drive.google.com/file/d/0B2-GEXllJCUZZVlDQnlsWng0dm8/view?usp=sharing

**Comment by Castaglia** [comment]
@tspicer Err...what file format is that `sq.log` file?
```
$ less sql.log 
"sql.log" may be a binary file.  See it anyway? 
```

From the `proftpd_trace_a (1).log` file, I see SFTP `OPEN` requests for "foo.zip"; since the `.zip` extension is *not* included in your deny filter, there would be no "failed" status logged:
```
<regexp:9>: PCRE regex '^.*\.(ade|adp|app|ai|asa|a
shx|asmx|asp|bas|bat|cdx|cer|cgi|chm|class|cmd|com|config|cpl|crt|csh|dmg|doc|do
cx|dll|eps|exe|fxp|ftpaccess|ftaccess|gif|hlp|hta|htr|htaccess|htw|html|htm|ida|
idc|idq|ins|isp|iso|its|jsp|jsf|java|jse|ksh|lnk|mad|maf|mag|mam|maq|mar|mas|mat
|mau|mav|maw|mda|mdb|mde|mdt|mdw|mdz|mp4|mov|msc|msh|msh1|msh1xml|msh2|msh2xml|m
shxml|msi|msp|mst|ops|pdf|php|php3|php4|php5|pcd|pl|py|pif|prf|prg|printer|pst|p
sd|rar|reg|rem|scf|scr|sct|sh|shb|shs|shtm|shtml|soap|stm|sql|tgz|taz|url|vb|vbe
|vbs|ws|wsc|wsf|wsh|xls|xlsx|xvd)$' failed to match subject '/.open_gapps-arm-7.
0-aroma-2017020333a.zip': subject did not match pattern
```

**Comment by tspicer** [comment]
Not sure what happened. SQL Log: https://drive.google.com/file/d/0B2-GEXllJCUZaDVZdm1NbU01V28/view?usp=sharing

Yes, the ZIP is allowed. However, I killed the transfer which yesterday resulted in success. 

I'm going to re-run everything and run a test with allowed and disallowed files to mimic the original issue. I will repost fresh logs

**Comment by Castaglia** [comment]
I guess the question is what the SFTP client in question does when you "kill the transfer".  Does the client send a nice `CLOSE` SFTP request -- in which case, there's _no way for `mod_sftp` to know that anything went wrong_?  Or did the client abruptly terminate its TCP connection?  I'm guessing for the former...

**Pull request merged**
