### PR TITLE
fix build with gcc 15

### PR DESCRIPTION
**Pull request by heitbaum**
dont use reserved type word bool as a variable name

### CODE REVIEW

**Comment by Castaglia** [comment]
Hmm.  I might go through these occurrences and choose a different variable name.

What's the distribution/platform that you're using, that is using gcc 15, so that I can reproduce/fix these issues locally?

**Comment by heitbaum** [comment]
> Hmm. I might go through these occurrences and choose a different variable name.

I did think that might be the way to go - was just to get a start.

> What's the distribution/platform that you're using, that is using gcc 15, so that I can reproduce/fix these issues locally?

I'm building for LibreELEC - https://github.com/LibreELEC/LibreELEC.tv - in the Ubuntu 24.04 (with a gcc cross compiler.) https://wiki.libreelec.tv/development/build-docker#basic (I do most of the LE distro package management.)

**Comment by Castaglia** [comment]
> > Hmm. I might go through these occurrences and choose a different variable name.
> 
> I did think that might be the way to go - was just to get a start.

Thanks, it's much appreciated!

> > What's the distribution/platform that you're using, that is using gcc 15, so that I can reproduce/fix these issues locally?
> 
> I'm building for LibreELEC - https://github.com/LibreELEC/LibreELEC.tv - in the Ubuntu 24.04 (with a gcc cross compiler.) https://wiki.libreelec.tv/development/build-docker#basic (I do most of the LE distro package management.)

I managed to use an Ubuntu 25.04 Docker image locally, in combination with a PPA, to get a gcc-15 installation.  With that, I validated https://github.com/proftpd/proftpd/pull/1858, which should be functionally identical (with some accompanying stylistic changes as well).  Could you verify that it also works for your needs?

**Comment by heitbaum** [comment]
> > > Hmm. I might go through these occurrences and choose a different variable name.
> > 
> > 
> > I did think that might be the way to go - was just to get a start.
> 
> Thanks, it's much appreciated!
> 
> > > What's the distribution/platform that you're using, that is using gcc 15, so that I can reproduce/fix these issues locally?
> > 
> > 
> > I'm building for LibreELEC - https://github.com/LibreELEC/LibreELEC.tv - in the Ubuntu 24.04 (with a gcc cross compiler.) https://wiki.libreelec.tv/development/build-docker#basic (I do most of the LE distro package management.)
> 
> I managed to use an Ubuntu 25.04 Docker image locally, in combination with a PPA, to get a gcc-15 installation. With that, I validated #1858, which should be functionally identical (with some accompanying stylistic changes as well). Could you verify that it also works for your needs?

- Tested #1858 along with c07b4aaad575c070f6456413e5f5b73697d50e3c and had a successful crosscompile with gcc-15

**Comment by Castaglia** [comment]
Closing this as superseded.  Thanks!

**Pull request closed without merging**
