### PR TITLE
contrib: Update tls_mod for LibreSSL 3.5

### PR DESCRIPTION
**Pull request by orbea**
Tested with libressl-3.5.3.

Instead of making this a bigger mess I decided to not care about older libressl versions, but I can make effort to change that if someone really cares. :)

### CODE REVIEW

**Comment by Castaglia** [comment]
On what platforms are you using LibreSSL 3.5?  I'd like to see if it'd be possible to add that combination to the GitHub Actions CI workflow.  Thanks!

**Comment by orbea** [comment]
I'm using it on Gentoo using the libressl overlay.

https://github.com/gentoo/libressl

The current situation is that the primary libressl user is OpenBSD and most linux distros dropped support, but I am trying to keep it working on Gentoo.

**Comment by ffontaine** [comment]
It should be noted that `mod_sftp` also fails to build with libressl 3.5.

The most important issue is that `EVP_CIPHER_CTX` is opaque since https://github.com/libressl/openbsd/commit/3f84934ae67f005ce128c593cc9ec7fd7d3c80c5 however libressl doesn't provide any `EVP_CIPHER_meth_set_{iv_length,init,cleanup,do_cipher}`.

So, the update to `cipher.c` is not trivial.
Given that this PR on `tls_mod` hasn't been merged, do you plan on supporting libressl >= 3.5 or should I disable mod_sftp with libressl on buildroot?

**Comment by Castaglia** [comment]
I'm currently looking through these changes, and the LibreSSL ChangeLog, with an eye toward the cost of code complexity, caused by maintaining compatibility with _both_ OpenSSL and LibreSSL across their versions.  It's getting to be painful.  So the questions I have to ask, @orbea are these:
* Why continue to use to LibreSSL instead of OpenSSL?
* For your LibreSSL needs, how many old LibreSSL versions need to be supported, and why?

**Comment by Castaglia** [comment]
Would you care to see if https://github.com/proftpd/proftpd/pull/1587 meets your needs?

**Comment by Castaglia** [comment]
I'm going to close this PR, in favor of https://github.com/proftpd/proftpd/pull/1587.  Thanks for the feedback/prompt on updating ProFTPD for newer LibreSSL versions.

**Pull request closed without merging**
