### PR TITLE
Issue #1018: Ensure that the permissions of the PidFile are never wor…

### PR DESCRIPTION
**Pull request by Castaglia**
…ld-writable, regardless of Umask.

### CODE REVIEW

**Comment by d-schramm** [comment]
@Castaglia There's an error message now, but the PID is created with the correct permissions. However, the PidFile directive seems to be ignored (this might be unrelated!). I have this in my proftpd.conf:
   PidFile /var/run/proftpd/proftpd.pid

```
# /usr/local/proftpd-1.3.7-master/sbin/proftpd -n
2020-05-21 16:00:03,778 ops001 proftpd[20006] thehostname: ProFTPD 1.3.7rc4 (git) (built Thu May 21 2020 15:56:21 CEST) standalone mode STARTUP
error setting permissions for PidFile '/usr/local/proftpd-1.3.7-master//var/proftpd.pid': Operation not permitted
...
# ls -lA /usr/local/proftpd-1.3.7-master/var/
total 12
-rw-r--r--  1 root root    6 May 21 16:00 proftpd.pid
# ls -lA /var/run/proftpd/
total 0
#
```

This is the configuration file:

```
ServerType                      standalone
UseIPv6                         off
User                            proftpd
Group                           nogroup
PidFile                         /var/run/proftpd/proftpd.pid
DelayTable                      /var/run/proftpd/proftpd.delay
ScoreboardFile                  /var/run/proftpd/proftpd.scoreboard
Umask                           000  000
```

**Comment by d-schramm** [comment]
Here are the compile-time settings. I see that the PID and scoreboard file paths are compiled in. I forgot to mention above that the files proftpd.delay and proftpd.scoreboard were present on startup, but also in /usr/local/proftpd-1.3.7-master/var/ -- despite the configured paths.

```
# /usr/local/proftpd-1.3.7-master/sbin/proftpd -V
Compile-time Settings:
  Version: 1.3.7rc4 (git)
  Platform: LINUX [Linux 5.3.0-51-generic x86_64]
  Built: Thu May 21 2020 15:56:21 CEST
  Built With:
    configure  '--prefix=/usr/local/proftpd-1.3.7-master/'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib  -rdynamic
  LIBS:  -lpam -lsupp -lcrypt -ldl

  Files:
    Configuration File:
      /usr/local/proftpd-1.3.7-master//etc/proftpd.conf
    Pid File:
      /usr/local/proftpd-1.3.7-master//var/proftpd.pid
    Scoreboard File:
      /usr/local/proftpd-1.3.7-master//var/proftpd.scoreboard

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    - Controls support
    - curses support
    - Developer support
    - DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    - NLS support
    - OpenSSL support
    - PCRE support
    - POSIX ACL support
    - Redis support
    + Sendfile support
    + Shadow file support
    - Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

#
```

**Comment by Castaglia** [comment]
@d-schramm Thanks for the info.  I've updated the PR, to hopefully address the "operation not permitted" errors you see.

**Comment by d-schramm** [comment]
@Castaglia yes, that fixes the "error setting permissions". And the PID file still has the correct permissions. Problem solved, it seems.

**Pull request merged**
