### PR TITLE
Enable mod ldap extensions

### PR DESCRIPTION
**Pull request by ws0w**
Related to issue: #546

The purpose of this modification is to enable extensions to mod_ldap, without having to re-implement LDAP authentication. 

By exposing two variables and one function in mod_ldap.h, new modules can leverage the existing LDAP authentication and focus only on the new feature(s) to be added.

This mod exposes the following through a new mod_ldap.h file:

extern LDAP *ld;
extern char *ldap_authbind_dn;
extern int pr_ldap_connect(LDAP **, int);

### CODE REVIEW

**Comment by Castaglia** [comment]
Shouldn't `contrib/mod_ldap.c` now `#include` the new header, to keep the function signatures and data types in sync, as well?

**Comment by ws0w** [comment]
Yes, it should.

**Comment by ws0w** [comment]
My requirements have been changing, and the code change in this pull request is no longer sufficient. I've copied mod_ldap into a new module, mod_ldapauth, and am now making my changes there.

So, I'm not sure if this pull request is worth spending any more time on.

**Comment by ws0w** [comment]
No longer relevant.

**Pull request closed without merging**
