### PR TITLE
Bug #4185: Create directive for tuning the presence/absence of fields…

### PR DESCRIPTION
**Pull request by Castaglia**
… in the

default ProFTPD syslog/module logging.

### CODE REVIEW

**Comment by pghmcfc** [comment]
I was about to request an option for dropping the `proftpd[pid] ` too...

This is with systemd and `LogOptions -Timestamp -Hostname`
```
May 04 14:04:32 ftpserver.city-fan.org systemd[1]: Starting ProFTPD FTP Server...
May 04 14:04:32 ftpserver.city-fan.org proftpd[2187247]: Checking syntax of configuration file
May 04 14:04:32 ftpserver.city-fan.org systemd[1]: Started ProFTPD FTP Server.
May 04 14:04:32 ftpserver.city-fan.org proftpd[2187248]: proftpd[2187248] ftpserver.city-fan.org: ProFTPD 1.3.7rc3 (devel) (built Mon May 4 2020 13:59:22 BST) standalone mode STARTUP
May 04 14:05:17 ftpserver.city-fan.org proftpd[2187248]: proftpd[2187261] ftpserver.city-fan.org (ftpclient.city-fan.org[2001:...::24]): FTP session opened.
May 04 14:05:24 ftpserver.city-fan.org proftpd[2187248]: proftpd[2187261] ftpserver.city-fan.org (ftpclient.city-fan.org[2001:...::24]): USER paul: Login successful.
May 04 14:05:28 ftpserver.city-fan.org proftpd[2187248]: proftpd[2187261] ftpserver.city-fan.org (ftpclient.city-fan.org[2001:...::24]): FTP session closed.
```
... but I noticed that `proftpd` is logging the PID of the process serving the client and `systemd` is just logging the pid of the master process so they're both useful values, albeit slightly confusing at first glance.

**Comment by Castaglia** [comment]
Thanks for trying out the PR, @pghmcfc .  So in your opinion, will this meet your current `systemd` needs/use case?

**Comment by pghmcfc** [comment]
It's OK for me but I asked the reporter of my original issue (https://bugzilla.redhat.com/show_bug.cgi?id=1808989) to comment too.

**Comment by pghmcfc** [comment]
I think it would be a good idea to add a `-Pid` option to drop the "proftpd[PID]: "  part of the log message. Whilst it does contain information that `systemd `doesn't provide, I can certainly envisage some people not wanting to see it given that `systemd` does provide the main process pid.

**Comment by Castaglia** [comment]
@pghmcfc unfortunately, if the session-specific PID is omitted from the log message, there will not be anything to differentiate the multiple sessions from each other in the `systemd` logs, which I feel will create more confusion and work later, for folks trying to provide `systemd` logs for debugging issues -- and we won't be able to tell one session from another.  The master PID is not sufficient, IMHO.

**Comment by pghmcfc** [comment]
@Castaglia I see where you're coming from there. Maybe if that PID could be made to look less like a duplicate it might look better? Something like changing the "proftpd" to "master" or "child" depending on which process logged the message?

**Comment by Castaglia** [comment]
That approach would work - but only because `systemd` is using a _different_ label, _i.e._ "proftpd", for its logging of that master PID.  This is getting into the area where `systemd`-specific details are imposing constraints on ProFTPD logging even more -- and there _are_ other process managers than `systemd`.

**Comment by Castaglia** [comment]
One possibility is to change the "proftpd[$PID]" permanently, in the ProFTPD logging, to use _e.g._ "daemon[$PID]" and "session[$PID]", I suppose.  I expect that this would cause compatibility issues for custom ProFTPD log parsers out there.

**Comment by pghmcfc** [comment]
Unless there was a `LogOption` to leave it as "proftpd[$PID]"...

**Comment by Castaglia** [comment]
True.  Hmm.  Maybe something like this?
```
LogOptions -Timestamp -Hostname +RoleBasedProcessLabels
```
where the "role-based" process labels would be "daemon" and "session", _vs_ "proftpd" for both.  Think that'd be understandable, clear?

**Comment by pghmcfc** [comment]
Yes, that looks OK to me.

**Comment by Castaglia** [comment]
@pghmcfc PR now updated with the suggested `RoleBasedProcessLabels` option, for your testing.

**Comment by pghmcfc** [comment]
Logging now looks like this:
```
May  9 13:15:39 ftpserver proftpd[2544603]: Checking syntax of configuration file
May  9 13:15:39 ftpserver proftpd[2544604]: daemon[2544604] ftpserver.city-fan.org: ProFTPD 1.3.7rc3 (devel) (built Sat May 9 2020 13:10:04 BST) standalone mode STARTUP
May  9 13:16:33 ftpserver proftpd[2544604]: session[2544699] ftpserver.city-fan.org (ftpclient.city-fan.org[2001:...::24]): FTP session opened.
May  9 13:16:41 ftpserver proftpd[2544604]: session[2544699] ftpserver.city-fan.org (ftpclient.city-fan.org[2001:...::24]): USER paul: Login successful.
May  9 13:16:50 ftpserver proftpd[2544604]: session[2544699] ftpserver.city-fan.org (ftpclient.city-fan.org[2001:...::24]): FTP session closed.
```
I don't think there's much can be done to improve that.

**Pull request merged**
