### PR TITLE
Issue #1325: When processing matched globbed paths for `NLST`, make s…

### PR DESCRIPTION
**Pull request by Castaglia**
…ure we properly differentiate between hidden dotfiles and paths with `./` prefaces.

### CODE REVIEW

**Comment by Sashan** [comment]
Hello,
I just gave it a try. works well for `test/test_000?.dat` and `./test/test_000?.dat`. However there is still inconsistency, if directory `test` gets changed to `.test`. See terminal output here:
```
ftp> ls .test/
229 Entering Extended Passive Mode (|||62302|)
150 Opening ASCII mode data connection for file list
.test/test_0008.dat
.test/test_0006.dat
.test/test_0001.dat
.test/test_0007.dat
.test/test_0009.dat
.test/test_0004.dat
.test/test_0003.dat
.test/test_0002.dat
.test/test_0005.dat
226 Transfer complete
remote: .test/
189 bytes received in 0.0069 seconds (26.84 Kbytes/s)
ftp> ls .test/test_000?.dat
229 Entering Extended Passive Mode (|||51123|)
150 Opening ASCII mode data connection for file list
226 Transfer complete
ftp> ls ./.test/test_000?.dat
229 Entering Extended Passive Mode (|||35279|)
150 Opening ASCII mode data connection for file list
./.test/test_0005.dat
./.test/test_0002.dat
./.test/test_0003.dat
./.test/test_0004.dat
./.test/test_0009.dat
./.test/test_0007.dat
./.test/test_0001.dat
./.test/test_0006.dat
./.test/test_0008.dat
226 Transfer complete
remote: ./.test/test_000?.dat
207 bytes received in 0.0029 seconds (69.72 Kbytes/s)
```

I think that the `strncmp("./", 2) != 0` should not be there. If I remove it I see consistent output for all `ls` commands in example above. the extra `strcmp()` makes `ls .test/test_000?.dat` to report no results.

**Comment by Castaglia** [comment]
Actually, I think the fact that `NLST .test/` returns a list of files is unexpected; that `.test` directory is a Unix "hidden file", and thus shouldn't be listed (unless the `-A` list option is provided).

**Comment by Castaglia** [comment]
PR updated to remove the checking for hidden files in the `ls_nlst()` function; such checks are already implemented in the `nlstdir()` and `nlstfile()` functions, where they should be.  With this update, the original test case, and the new test cases using a `.test` directory, work as expected.

**Comment by Sashan** [comment]
Hello,

gave a try to the most recent version (with the whole condition removed). Works as expected.
thank you for quick turnaround on this.

**Pull request merged**
