### PR TITLE
use port as before calling to config_write()

### PR DESCRIPTION
**Pull request by Sashan**

### CODE REVIEW

**Comment by Castaglia** [comment]
Why make this particular change?  Please provide full explanations for these changes, as the diffs themselves may not be clear.

**Comment by Sashan** [comment]
> 

this is what happens when we run test as found in current master branch:
```
Failed 1/2 subtests 

Test Summary Report
-------------------
t/signals/hup.t (Wstat: 0 Tests: 2 Failed: 1)
  Failed test:  1
Files=1, Tests=2, 15 wallclock secs ( 0.05 usr  0.05 sys +  0.51 cusr  0.71 csys =  1.32 CPU)
Result: FAIL
Failed 1/1 test programs. 1/2 subtests failed.
```

the failing test case is `hup_daemon_ok()`, details on error are as follows:
```
Net::FTP>>> Net::FTP(3.11)                                                                                                                                                                                                                       
Net::FTP>>>   Exporter(5.74)                                                                                                                                                                                                                     
Net::FTP>>>   Net::Cmd(3.11)                                                                                                                                                                                                                     
Net::FTP>>>   IO::Socket::IP(0.39)                                                                                                                                                                                                               
Net::FTP>>>     IO::Socket(1.43)                                                                                                                                                                                                                 
Net::FTP>>>       IO::Handle(1.42)                                                                                                                                                                                                               
Net::FTP=GLOB(0x193dd8be8)<<< 220 foo                                                                                                                                                                                                            
Restarting server: kill -HUP 3235                                                                                                                                                                                                                
Use of uninitialized value $port in concatenation (.) or string at t/lib/ProFTPD/TestSuite/FTP.pm line 52.                                                                                                                                       
                                                                                                                                                                                                                                                 
not ok ERROR hup_daemon_ok                                                                                                                                                                                                                       
t/lib/ProFTPD/Tests/Signals/HUP.pm:96 - hup_daemon_ok(ProFTPD::Tests::Signals::HUP)   
```

my understanding is that code at line 92 returns an empty value to local variable port making call to `FTP->new()` to fail with error above.
```
 89                                                                                                                                                                                                                                              
 90   # Now change the config a little, and send the HUP signal                                                                                                                                                                                  
 91   $config->{ServerIdent} = 'on bar';                                                                                                                                                                                                         
 92   ($port, $config_user, $config_group) = config_write($config_file, $config);                                                                                                                                                                
 93   server_restart($pid_file);                                                                                                                                                                                                                 
 94   sleep(2);                                                                                                                                                                                                                                  
 95                                                                                                                                                                                                                                              
 96   $client = ProFTPD::TestSuite::FTP->new('127.0.0.1', $port);                                                                                                                                                                                
 97                                                                                  
```

I did not poke to `config_write()` function enough to understand its logic why it returns port uninitialized. from what I could see there I can tell that `$port` is not always set on its return.

**Comment by Castaglia** [comment]
This issue should be fixed by https://github.com/proftpd/proftpd/commit/d9c8e6733ec47d7f36052bcacea78dfd32568a63 -- which includes a comment explaining why the first `$port` file needs to be used for this regression test.

**Comment by Sashan** [comment]
> This issue should be fixed by [d9c8e67](https://github.com/proftpd/proftpd/commit/d9c8e6733ec47d7f36052bcacea78dfd32568a63) -- which includes a comment explaining why the first `$port` file needs to be used for this regression test.

Thanks for the comment which makes things very clear now.

**Pull request closed without merging**
