### PR TITLE
Add detailed error message for pr_display_file()

### PR DESCRIPTION
**Pull request by byshen**
pr_display_file() could fail for multiple reasons; adding detailed log messages would help admins debugging the error.

### CODE REVIEW

**Comment by byshen** [comment]
@Castaglia I am not sure why it fails on freebsd-12-2  during the `pkginstall` step. Please let me know how I can fix it. Thanks!

**Comment by Castaglia** [comment]
> @Castaglia I am not sure why it fails on freebsd-12-2 during the `pkginstall` step. Please let me know how I can fix it. Thanks!

I wouldn't worry too much about that; sometimes the FreeBSD VM support provided by CirrusCI is flaky.  As long as most of the other Linux checks succeed (especially with the FreeBSD 11.x build passing), it's safe to assume that the code will work across most platforms.

**Comment by Castaglia** [comment]
The main consumers/users of the `pr_display_file()` function already do log, at debug level 6, the errors.  As such, I think this additional logging via `pr_log_debug()` might be redundant.

That _said_, for the different error cases it, it might be useful to instead use `pr_trace_msg()`, and log these errors using Trace logging, to a "display" trace channel.  Thoughts?

**Comment by byshen** [comment]
> That _said_, for the different error cases it, it might be useful to instead use `pr_trace_msg()`, and log these errors using Trace logging, to a "display" trace channel. Thoughts?

I agree. I will change the logging level to trace level to provide additional information. Thank you for the review!

**Comment by byshen** [comment]
Hi TJ, I have changed the logging level based on your suggestion. Please let me know if any other change is needed. Thanks!

**Pull request merged**
