### PR TITLE
Support deletion-on-failure, for a failed copy.

### PR DESCRIPTION
**Pull request by Castaglia**
Addresses Issue #314 .

### CODE REVIEW

**Comment by uschaufelberger** [comment]
Sweet, thanks a lot for this enhancement, which works fine on single files.
However, delete on failed SITE copy currently fails when the source / target is a directory, tracing giving me:
`2016-08-04 15:48:48,964 [22889] <response:7>: error response added to pending list: 552 CPTO: Disk quota exceeded
2016-08-04 15:48:48,964 [22889] <fsio:8>: using system unlink() for path '/dst'
2016-08-04 15:48:48,964 [22889] <copy:7>: error deleting failed copy '/dst': Is a directory
`

**Comment by Castaglia** [comment]
Ah, yes -- excellent catch.  I'll adjust this, as part of working [Bug#4263](http://bugs.proftpd.org/show_bug.cgi?id=4263], as it will involve adjusting the signature of the core `pr_fs_file_copy()` function.

**Comment by Castaglia** [comment]
@uschaufelberger to address this, I will have to change the added `CopyOptions DeleteOnFailure` option.  Turns out that the `pr_fs_copy_file()` function _already deleted the destination on failure_ -- just not *all* of the failure cases.  So that, actually, was the root cause.

In fixing that, I am thinking to change the directive to be `CopyOptions NoDeleteOnFailure`, for any sites who do *not* want the deletion-on-failure capability.  Make sense?

**Comment by dup2** [comment]
Makes perfectly sense for me. Most sites will prefer the cleanup now done by default with the inverted option.

**Comment by Castaglia** [comment]
This functionality (auto-delete-on-failure, with optional no-delete-on-failure configurable via `CopyOptions`) is now available in the master branch.

**Pull request merged**
